name: recall
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip=24.2
  - pip:
    - tensorflow-gpu==2.6.0
    - numpy==1.21.0
    - scipy==1.10.1
    - pandas==2.0.3
    - matplotlib==3.7.5
    - seaborn==0.13.2
    - gymnasium==1.0.0
    - gym==0.26.2
    - cloudpickle==3.1.1
    - mujoco==2.3.0
    - pygame==2.6.1
    - PyOpenGL==3.1.9
    - protobuf==3.20.0
    - tensorboard==2.14.0
    - absl-py==0.15.0
    - astunparse==1.6.3
    - flatbuffers==1.12
    - gast==0.4.0
    - grpcio==1.70.0
    - h5py==3.1.0
    - keras==2.6.0
    - Keras-Preprocessing==1.1.2
    - six==1.15.0
    - termcolor==1.1.0
    - wrapt==1.12.1
    - -e ./metaworld
    - -e . 